#!/bin/bash

source $PLUG_PATH/util

# global
set_cfg EDITOR              "nvim"

# cmdr
set_cfg CMDR_CMDS_PATH      "$PROJ/cmds"
set_cfg CMDR_EXEC_FILE      "/tmp/exec.cmds"
set_cfg CMDR_EXEC_SHELL     "/bin/bash"
set_cfg CMDR_TEMP_CMDS      "/tmp/cmds.tmp"

# days
set_cfg DAYS_DIR            "$PROJ/days"
set_cfg DAYS_START_DATE     "1997-08-31"

# hold
set_cfg HOLD_DIR            "/tmp"
set_cfg HOLD_TIME           "1"
