#!/bin/bash

source $PLUG_PATH/cfgs

help_msg() {
    log "
    cmdr: the command runner
    desc: manage, search and execute your commands
    help: cmdr [args]
    args:
        -e, --edit                  edit commands file
        -g, --grep    <regex>       grep for a particular command
        -x, --execute <regex>       execute a set of commands
        -a, --add     <regex>       add a set of commands to a file
        -h, --help                  display this help\
    "
}

cmdr_cfg() {
    cmdr_var_start='<:'
    cmdr_var_end=':>'
    cmdr_disp_start='<'
    cmdr_disp_end='>'
}

cmdr_all_cmds() {
    # add check if $CMDR_CMDS_PATH is a directory then awk in all the files in the directory
    if [ -d $CMDR_CMDS_PATH ]; then
    awk '/```.*#/{flag=1;next}/```/{flag=0}flag' $CMDR_CMDS_PATH/*
    else
    awk '/```.*#/{flag=1;next}/```/{flag=0}flag' $CMDR_CMDS_PATH
    fi
}

cmdr_format() {
    cmds_disp=${1//$cmdr_var_start/$cmdr_disp_start}
    cmds_disp=${cmds_disp//$cmdr_var_end/$cmdr_disp_end}
}

cmdr_display() {
    echo "$1" | awk -F "\n" '{print NR ". " $1}'
}

cmdr_grep() {
    [ ! -n "$1" ] && err "no regex provided"
    cmds=`cmdr_all_cmds | grep $1`
    [ "$cmds" == "" ] && err "no commands found"
    cmdr_format "$cmds"
    cmdr_display "$cmds_disp"
}

cmdr_exec() {
    cmdr_grep "$1"
    selected_cmds=$(cmdr_select_cmds "$cmds")
    echo "#! $CMDR_EXEC_SHELL" > $CMDR_EXEC_FILE
    echo "$selected_cmds" >> $CMDR_EXEC_FILE
    chmod +x $CMDR_EXEC_FILE
    $CMDR_EXEC_FILE
    rm $CMDR_EXEC_FILE
}

cmdr_add() {
    cmdr_grep "$1"
    selected_cmds=$(cmdr_select_cmds "$cmds")
    [ ! -n "$CMDR_TEMP_CMDS" ] && err "CMDR_TEMP_CMDS not set" && exit 1
    echo "$selected_cmds" > $CMDR_TEMP_CMDS
}

cmdr_final_cmd() {
    entry=$1
    cmd=$1
    while [[ $entry =~ $cmdr_var_start ]]; do
        entry=${entry#*$cmdr_var_start}
        key=${entry%%$cmdr_var_end*}

        read -p "$key: " val
        [ ! -n "$val" ] && echo "err: no value provided" && exit 1

        cmd=${cmd/$cmdr_var_start$key$cmdr_var_end/$val}
    done
    echo "$cmd"
}

cmdr_select_cmds() {
    selected_cmds=""
    read -p "Enter command numbers (separate by space): " cmd_nums
    for cmd_num in $cmd_nums; do
        cmd=$(echo "$1" | sed -n "${cmd_num}p")
        cmdr_format "$cmd"
        final_cmd=$(cmdr_final_cmd "$cmd")
        echo "echo \"$cmd_num ...\""
        echo "$final_cmd"
    done
    echo "echo \"done.\""
}

prereqs() {
    cmdr_cfg
    check_dir $CMDR_CMDS_PATH
}

options() {
    case $1 in
        -e | --edit    ) edit $CMDR_CMDS_PATH;;
        -g | --grep    ) cmdr_grep "$2";;
        -a | --add     ) cmdr_add "$2";;
        -x | --execute ) cmdr_exec "$2";;
           *           ) help_msg;;
    esac
}

init $@
