#!/bin/bash

CMDR_CMDS_FILE="./cmds.md"
CMDR_EDITOR='vim'

CMDR_EXEC_FILE="./cmdr_exec.sh"
CMDR_SRC_FILE="./cmdr_src.sh"

CMDR_VAR_START='<:'
CMDR_VAR_END=':>'
CMDR_DISP_START='<'
CMDR_DISP_END='>'

cmdr_help() {
    echo "\
    cmdr: the command runner
    desc: manage, search and execute your commands
    help: cmdr [args]
    args:
        -e, --edit              edit commands file
        -g, --grep    <regex>   grep for a particular command
        -x, --execute <regex>   execute a set of commands
        -s, --source  <regex>   source a set of commands
        -h, --help              display this help\
    " | sed 's/^    //'
}

cmdr_err() {
    echo "err: $1"
    exit 1
}

cmdr_all_cmds() {
    awk '/```./{flag=1;next}/```/{flag=0}flag' $CMDR_CMDS_FILE
}

cmdr_format() {
    cmds_disp=${1//$CMDR_VAR_START/$CMDR_DISP_START}
    cmds_disp=${cmds_disp//$CMDR_VAR_END/$CMDR_DISP_END}
}

cmdr_display() {
    echo "$1" | awk -F "\n" '{print NR ". " $1}'
}

cmdr_grep() {
    [ ! -n "$1" ] && cmdr_err "no regex provided"
    cmds=`cmdr_all_cmds | grep $1`
    [ "$cmds" == "" ] && cmdr_err "no commands found"
    cmdr_format "$cmds"
    cmdr_display "$cmds_disp"
}

cmdr_exec() {
    cmdr_grep "$1"
    selected_cmds=$(cmdr_select_cmds "$cmds")
    echo "$selected_cmds" > $CMDR_EXEC_FILE
    chmod +x $CMDR_EXEC_FILE
    $CMDR_EXEC_FILE
    rm $CMDR_EXEC_FILE
}

cmdr_final_cmd() {
    entry=$1
    cmd=$1
    while [[ $entry =~ $CMDR_VAR_START ]]; do
        entry=${entry#*$CMDR_VAR_START}
        key=${entry%%$CMDR_VAR_END*}

        read -p "$key: " val
        [ ! -n "$val" ] && echo "err: no value provided" && exit 1

        cmd=${cmd/$key/$val}
        cmd=${cmd/$CMDR_VAR_START/}
        cmd=${cmd/$CMDR_VAR_END/}
    done
    echo "$cmd"
}

cmdr_select_cmds() {
    selected_cmds=""
    read -p "Enter command numbers (separate by space): " cmd_nums
    for cmd_num in $cmd_nums; do
        cmd=$(echo "$1" | sed -n "${cmd_num}p")
        cmdr_format "$cmd"
        final_cmd=$(cmdr_final_cmd "$cmd")
        echo "$final_cmd"
    done
}

[ ! -n "$1" ] && cmdr_help && exit 0

case $1 in
    --edit | -e)
        $CMDR_EDITOR $CMDR_CMDS_FILE
        ;;
    --grep | -g)
        cmdr_grep "$2"
        ;;
    --source | -s)
        ;;
    --execute | -x)
        cmdr_exec "$2"
        ;;
    --help | -h)
        cmdr_help
        ;;
    *)
        cmdr_err "not an arg: $1"
        ;;
esac
