#!/bin/bash

source $PLUG_PATH/cfgs

help_msg() {
    echo "\
    knot: the task notifier
    desc: notify next task initialization when previous task is finished
    help: knot [args]
    args:
        -c, --create <knot>         finish task and create the knot
        -t, --till   <knot>         standby task until knot created
        -u, --usage                 show examples of usage
        -h, --help                  display this help\
    "
}

examples() {
    echo "\
    example 1:
        Use knots to schedule task1 and task2,
        where task2 is dependent on task1.
        Start task1 and create a knot:
        $ task1 && knot -c
        Wait till knot is created and start task2:
        $ knot -t && task2
    example 2:
        Use knot names to schedule multiple tasks:
        $ task1 && knot -c k1
        $ knot -t k1 && task2 && knot -c k2
        $ knot -t k2 && task3\
    " | sed 's/^    //'
}

prereqs() {
    check_dir $KNOT_DIR
    knot_event="$KNOT_DIR/delete_me"
}

create() {
    if [ -n "$1" ]; then
        knot_event="$KNOT_DIR/$1_delete_me"
    fi
    touch $knot_event
}

till() {
    if [ -n "$1" ]; then
        knot_event="$KNOT_DIR/$1_delete_me"
    fi
    while true; do
        if [ -f "$knot_event" ]; then
            break
        fi
        sleep $KNOT_TIME
    done
    rm $knot_event
}

options() {
    case $1 in
        -c | --create ) create $2;;
        -t | --till   ) till $2;;
        -u | --usage  ) examples;;
           *          ) help_msg;;
    esac
}

init $@
